[package]
name = "place-segments-on"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
chrono = "0.4.38"
eframe = "0.28.1"
egui = "0.28.1"
egui_dnd = "0.9.0"
gethostname = "0.5.0"
users = "0.11.0"
